In [ ]:
1.
p(ins)=0.7
p(ins / smoker)=0.4
P(A) = (0.4 * P(A)) + (0.3 * (1 - P(A)))
p(smoker)=.3

p(smoker /ins )=p(s)*p(i/s)/p(i)=.3*.4/.7=17.14%

In [ ]:
2.
Bernoulli Naive Bayes: this is used fot Bernoulli datatype of data
it ignoring number of occurrences
it may cause some error comapratred Multinomial

Multinomial Naive Bayes: this is used for text datatype model 
track of multiple occurrences
it has low error compared to Bernoulli Naive Bayes

In [ ]:
3.Bernoulli Naive Bayes apparently handles missing data differently, depending on whether they exist in training or testing/classification instances

In [ ]:
4.we can use Gaussian Naive Bayes for multi class classification

In [2]:
5.
import pandas as pd 
df=pd.read_csv("spambase.csv")
df

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278,1
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.000,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4596,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4597,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4598,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4599,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

In [5]:
y=df.iloc[:,-1:]
y

      1
0     1
1     1
2     1
3     1
4     1
...  ..
4595  0
4596  0
4597  0
4598  0
4599  0

[4600 rows x 1 columns]

In [6]:
x=df.drop("1",axis=1)
x

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.40,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.0,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.0,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.0,0.000,0.223,0.0,0.000,0.000,0.000,3.000,15,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.0,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88
4596,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14
4597,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118
4598,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78
4599,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)
import warnings
warnings.filterwarnings("ignore")

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import BernoulliNB,GaussianNB,MultinomialNB
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

In [26]:
b=GridSearchCV(BernoulliNB(),param_grid={},cv=10)
b.fit(x_train,y_train)
y_pred=b.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[632  49]
 [ 85 384]]
0.8834782608695653
              precision    recall  f1-score   support

           0       0.88      0.93      0.90       681
           1       0.89      0.82      0.85       469

    accuracy                           0.88      1150
   macro avg       0.88      0.87      0.88      1150
weighted avg       0.88      0.88      0.88      1150

In [27]:
b=GridSearchCV(GaussianNB(),param_grid={},cv=10)
b.fit(x_train,y_train)
y_pred=b.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[492 189]
 [ 21 448]]
0.8173913043478261
              precision    recall  f1-score   support

           0       0.96      0.72      0.82       681
           1       0.70      0.96      0.81       469

    accuracy                           0.82      1150
   macro avg       0.83      0.84      0.82      1150
weighted avg       0.85      0.82      0.82      1150

In [28]:
b=GridSearchCV(MultinomialNB(),param_grid={},cv=10)
b.fit(x_train,y_train)
y_pred=b.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[544 137]
 [112 357]]
0.7834782608695652
              precision    recall  f1-score   support

           0       0.83      0.80      0.81       681
           1       0.72      0.76      0.74       469

    accuracy                           0.78      1150
   macro avg       0.78      0.78      0.78      1150
weighted avg       0.79      0.78      0.78      1150

In [ ]:
Discussion:
    we chose BernoulliNB  beasuse it has accuracy , in this dataset TN is importtant so , it has high recall 
    
    [[632  49]
 [ 85 384]]
0.8834782608695653
              precision    recall  f1-score   support

           0       0.88      0.93      0.90       681
           1       0.89      0.82      0.85       469

    accuracy                           0.88      1150
   macro avg       0.88      0.87      0.88      1150
weighted avg       0.88      0.88      0.88      1150

In [ ]:
Conclusion:
    we have 99.34 % accracry, 88% of recall . using this model , we can create optimal model . also can be improve by training more data to it